import type { Item, User } from "./types";

const now = Date.now();
const hrs = (h: number) => new Date(now - h * 3600_000).toISOString();

export const CURRENT_USER_ID = "u_self";

export const users: User[] = [
  {
    id: "u_self",
    name: "You",
    avatarColor: "oklch(0.45 0.06 235)",
    trustScore: 320,
    karma: 280,
    rank: "Trusted Member",
    itemsReturned: 4,
    itemsReported: 7,
    fraudRisk: "Low",
    badges: ["First Return", "Verified", "Quick Responder"],
  },
  {
    id: "u_aria",
    name: "Aria Menon",
    avatarColor: "oklch(0.6 0.1 155)",
    trustScore: 910,
    karma: 860,
    rank: "Campus Guardian",
    itemsReturned: 18,
    itemsReported: 22,
    fraudRisk: "Low",
    badges: ["Campus Hero", "Honest Founder", "10+ Returns"],
  },
  {
    id: "u_dev",
    name: "Dev Sharma",
    avatarColor: "oklch(0.74 0.12 75)",
    trustScore: 740,
    karma: 690,
    rank: "Campus Hero",
    itemsReturned: 12,
    itemsReported: 14,
    fraudRisk: "Low",
    badges: ["Trusted", "Night Owl"],
  },
  {
    id: "u_ravi",
    name: "Ravi Kale",
    avatarColor: "oklch(0.55 0.08 300)",
    trustScore: 120,
    karma: 60,
    rank: "Helper",
    itemsReturned: 1,
    itemsReported: 3,
    fraudRisk: "Medium",
    badges: ["New Founder"],
  },
  {
    id: "u_flag",
    name: "Anon 4421",
    avatarColor: "oklch(0.6 0.1 25)",
    trustScore: -180,
    karma: -210,
    rank: "New Member",
    itemsReturned: 0,
    itemsReported: 9,
    fraudRisk: "Critical",
    badges: [],
  },
];

export const items: Item[] = [
  {
    id: "it_001",
    kind: "found",
    title: "Blue backpack with Marvel sticker",
    category: "Bags",
    description:
      "Found a blue backpack with a Marvel/Avengers sticker on the front pocket near the Central Library entrance.",
    date: hrs(3),
    location: "Central Library — Main Gate",
    building: "Central Library",
    tags: ["blue", "backpack", "sticker", "marvel"],
    color: "blue",
    condition: "Good",
    urgency: "normal",
    status: "open",
    postedBy: "u_aria",
    createdAt: hrs(3),
    hidden: [
      { label: "Brand", value: "Skybag" },
      { label: "Inner pocket contents", value: "calculator and a charger" },
      { label: "Sticker detail", value: "Iron Man on front pocket" },
      { label: "Distinguishing mark", value: "frayed left strap" },
    ],
  },
  {
    id: "it_002",
    kind: "lost",
    title: "Black leather wallet",
    category: "Wallets",
    description:
      "Lost my black wallet somewhere between the cafeteria and Lab Block C. Contains my ID and a few cards.",
    date: hrs(6),
    location: "Cafeteria → Lab Block C",
    building: "Cafeteria",
    tags: ["black", "wallet", "leather", "cards"],
    color: "black",
    condition: "Used",
    urgency: "critical",
    reward: 200,
    status: "open",
    postedBy: "u_self",
    createdAt: hrs(6),
    hidden: [
      { label: "Brand", value: "Tommy Hilfiger" },
      { label: "Number of cards", value: "3" },
      { label: "Cash range", value: "500-1000" },
      { label: "Hidden mark", value: "blue thread stitched inside" },
    ],
  },
  {
    id: "it_003",
    kind: "found",
    title: "Silver laptop in sleeve",
    category: "Electronics",
    description:
      "Found a silver laptop inside a grey sleeve left in Lecture Hall 2. Handed nothing in yet, verifying owner.",
    date: hrs(20),
    location: "Lecture Hall 2",
    building: "Academic Block",
    tags: ["silver", "laptop", "sleeve", "electronics"],
    color: "silver",
    condition: "Like New",
    urgency: "critical",
    status: "open",
    postedBy: "u_dev",
    createdAt: hrs(20),
    hidden: [
      { label: "Brand", value: "Dell" },
      { label: "Wallpaper", value: "mountain landscape at sunset" },
      { label: "Sticker count", value: "2" },
      { label: "Keyboard cover color", value: "transparent" },
    ],
  },
  {
    id: "it_004",
    kind: "found",
    title: "Steel water bottle with stickers",
    category: "Water Bottles",
    description: "Steel bottle covered in stickers found at the Sports Complex bench.",
    date: hrs(2),
    location: "Sports Complex",
    building: "Sports Complex",
    tags: ["steel", "bottle", "stickers"],
    color: "steel",
    condition: "Used",
    urgency: "normal",
    status: "open",
    postedBy: "u_ravi",
    createdAt: hrs(2),
    hidden: [
      { label: "Cap color", value: "black" },
      { label: "Stickers", value: "band logos and a smiley" },
      { label: "Scratches", value: "dent near base" },
      { label: "Name written", value: "P. on the cap" },
    ],
  },
  {
    id: "it_005",
    kind: "lost",
    title: "Set of keys with red tag",
    category: "Keys",
    description: "Lost my hostel keys with a red keychain tag near Hostel A stairs.",
    date: hrs(30),
    location: "Hostel A",
    building: "Hostel A",
    tags: ["keys", "red", "keychain"],
    color: "red",
    condition: "Used",
    urgency: "high",
    status: "open",
    postedBy: "u_self",
    createdAt: hrs(30),
    hidden: [
      { label: "Number of keys", value: "3" },
      { label: "Tag text", value: "Room 214" },
      { label: "Keychain shape", value: "round" },
    ],
  },
  {
    id: "it_006",
    kind: "found",
    title: "Student ID card",
    category: "ID Cards",
    description: "Found an ID card dropped near the Cafeteria counter.",
    date: hrs(1),
    location: "Cafeteria",
    building: "Cafeteria",
    tags: ["id", "card"],
    color: "white",
    condition: "Good",
    urgency: "high",
    status: "matched",
    postedBy: "u_aria",
    createdAt: hrs(1),
    hidden: [
      { label: "Department", value: "Computer Science" },
      { label: "Year", value: "3rd" },
    ],
  },
  {
    id: "it_007",
    kind: "lost",
    title: "Blue Skybag with Iron Man sticker",
    category: "Bags",
    description:
      "Lost my blue Skybag backpack with an Iron Man sticker. Had a calculator and charger inside. Last seen near the library.",
    date: hrs(5),
    location: "Central Library",
    building: "Central Library",
    tags: ["blue", "skybag", "iron man", "backpack", "sticker"],
    color: "blue",
    condition: "Good",
    urgency: "high",
    reward: 150,
    status: "open",
    postedBy: "u_self",
    createdAt: hrs(5),
    hidden: [
      { label: "Brand", value: "Skybag" },
      { label: "Inner pocket contents", value: "calculator and a charger" },
      { label: "Sticker detail", value: "Iron Man on front pocket" },
      { label: "Distinguishing mark", value: "frayed left strap" },
    ],
  },
];

export const buildingLossStats: { building: string; count: number; recovered: number }[] = [
  { building: "Central Library", count: 35, recovered: 24 },
  { building: "Cafeteria", count: 22, recovered: 18 },
  { building: "Hostel A", count: 17, recovered: 9 },
  { building: "Academic Block", count: 14, recovered: 11 },
  { building: "Sports Complex", count: 9, recovered: 5 },
  { building: "Lab Block C", count: 6, recovered: 4 },
];

export const peakLossHours = [
  { hour: "8a", count: 4 },
  { hour: "10a", count: 9 },
  { hour: "12p", count: 14 },
  { hour: "2p", count: 11 },
  { hour: "4p", count: 17 },
  { hour: "6p", count: 21 },
  { hour: "8p", count: 12 },
  { hour: "10p", count: 6 },
];

export const monthlyTrend = [
  { month: "Jan", lost: 40, returned: 28 },
  { month: "Feb", lost: 52, returned: 39 },
  { month: "Mar", lost: 48, returned: 37 },
  { month: "Apr", lost: 61, returned: 50 },
  { month: "May", lost: 55, returned: 47 },
  { month: "Jun", lost: 67, returned: 58 },
];

export function getUser(id: string): User {
  return users.find((u) => u.id === id) ?? users[0];
}

export function getItem(id: string): Item | undefined {
  return items.find((i) => i.id === id);
}
